export type CountryOption = {
  code: string;
  name: string;
  nativeCurriculum?: string | null;
};

export const COUNTRIES: CountryOption[] = [
  { code: "AF", name: "Afghanistan", nativeCurriculum: "Afghanistan National Curriculum" },
  { code: "AL", name: "Albania", nativeCurriculum: "Albania National Curriculum" },
  { code: "DZ", name: "Algeria", nativeCurriculum: "Algeria National Curriculum" },
  { code: "AD", name: "Andorra", nativeCurriculum: "Andorra National Curriculum" },
  { code: "AO", name: "Angola", nativeCurriculum: "Angola National Curriculum" },
  { code: "AR", name: "Argentina", nativeCurriculum: "Argentina National Curriculum" },
  { code: "AM", name: "Armenia", nativeCurriculum: "Armenia National Curriculum" },
  { code: "AU", name: "Australia", nativeCurriculum: "Australian Curriculum" },
  { code: "AT", name: "Austria", nativeCurriculum: "Austria National Curriculum" },
  { code: "AZ", name: "Azerbaijan", nativeCurriculum: "Azerbaijan National Curriculum" },
  { code: "BD", name: "Bangladesh", nativeCurriculum: "Bangladesh National Curriculum" },
  { code: "BE", name: "Belgium", nativeCurriculum: "Belgium National Curriculum" },
  { code: "BJ", name: "Benin", nativeCurriculum: "Benin National Curriculum" },
  { code: "BW", name: "Botswana", nativeCurriculum: "Botswana National Curriculum" },
  { code: "BR", name: "Brazil", nativeCurriculum: "Brazilian National Curriculum" },
  { code: "BG", name: "Bulgaria", nativeCurriculum: "Bulgaria National Curriculum" },
  { code: "BF", name: "Burkina Faso", nativeCurriculum: "Burkina Faso National Curriculum" },
  { code: "BI", name: "Burundi", nativeCurriculum: "Burundi National Curriculum" },
  { code: "KH", name: "Cambodia", nativeCurriculum: "Cambodia National Curriculum" },
  { code: "CM", name: "Cameroon", nativeCurriculum: "Cameroon National Curriculum" },
  { code: "CA", name: "Canada", nativeCurriculum: "Canada National Curriculum" },
  { code: "TD", name: "Chad", nativeCurriculum: "Chad National Curriculum" },
  { code: "CL", name: "Chile", nativeCurriculum: "Chile National Curriculum" },
  { code: "CN", name: "China", nativeCurriculum: "China National Curriculum" },
  { code: "CO", name: "Colombia", nativeCurriculum: "Colombia National Curriculum" },
  { code: "CG", name: "Congo", nativeCurriculum: "Congo National Curriculum" },
  { code: "CD", name: "Democratic Republic of the Congo", nativeCurriculum: "DRC National Curriculum" },
  { code: "CR", name: "Costa Rica", nativeCurriculum: "Costa Rica National Curriculum" },
  { code: "CI", name: "Côte d’Ivoire", nativeCurriculum: "Côte d’Ivoire National Curriculum" },
  { code: "HR", name: "Croatia", nativeCurriculum: "Croatia National Curriculum" },
  { code: "CY", name: "Cyprus", nativeCurriculum: "Cyprus National Curriculum" },
  { code: "CZ", name: "Czech Republic", nativeCurriculum: "Czech National Curriculum" },
  { code: "DK", name: "Denmark", nativeCurriculum: "Denmark National Curriculum" },
  { code: "DJ", name: "Djibouti", nativeCurriculum: "Djibouti National Curriculum" },
  { code: "EG", name: "Egypt", nativeCurriculum: "Egyptian National Curriculum" },
  { code: "ET", name: "Ethiopia", nativeCurriculum: "Ethiopian National Curriculum" },
  { code: "FI", name: "Finland", nativeCurriculum: "Finnish National Curriculum" },
  { code: "FR", name: "France", nativeCurriculum: "French National Curriculum" },
  { code: "DE", name: "Germany", nativeCurriculum: "Germany National Curriculum" },
  { code: "GH", name: "Ghana", nativeCurriculum: "Ghana Standards-Based Curriculum" },
  { code: "GR", name: "Greece", nativeCurriculum: "Greece National Curriculum" },
  { code: "IN", name: "India", nativeCurriculum: "CBSE" },
  { code: "ID", name: "Indonesia", nativeCurriculum: "Indonesia National Curriculum" },
  { code: "IE", name: "Ireland", nativeCurriculum: "Ireland National Curriculum" },
  { code: "IL", name: "Israel", nativeCurriculum: "Israel National Curriculum" },
  { code: "IT", name: "Italy", nativeCurriculum: "Italy National Curriculum" },
  { code: "JP", name: "Japan", nativeCurriculum: "Japan National Curriculum" },
  { code: "KE", name: "Kenya", nativeCurriculum: "CBC" },
  { code: "KR", name: "South Korea", nativeCurriculum: "South Korea National Curriculum" },
  { code: "LB", name: "Lebanon", nativeCurriculum: "Lebanon National Curriculum" },
  { code: "LS", name: "Lesotho", nativeCurriculum: "Lesotho National Curriculum" },
  { code: "LR", name: "Liberia", nativeCurriculum: "Liberia National Curriculum" },
  { code: "MG", name: "Madagascar", nativeCurriculum: "Madagascar National Curriculum" },
  { code: "MW", name: "Malawi", nativeCurriculum: "Malawi National Curriculum" },
  { code: "MY", name: "Malaysia", nativeCurriculum: "Malaysia National Curriculum" },
  { code: "ML", name: "Mali", nativeCurriculum: "Mali National Curriculum" },
  { code: "MX", name: "Mexico", nativeCurriculum: "Mexico National Curriculum" },
  { code: "MA", name: "Morocco", nativeCurriculum: "Morocco National Curriculum" },
  { code: "MZ", name: "Mozambique", nativeCurriculum: "Mozambique National Curriculum" },
  { code: "NA", name: "Namibia", nativeCurriculum: "Namibia National Curriculum" },
  { code: "NL", name: "Netherlands", nativeCurriculum: "Netherlands National Curriculum" },
  { code: "NZ", name: "New Zealand", nativeCurriculum: "New Zealand Curriculum" },
  { code: "NG", name: "Nigeria", nativeCurriculum: "Nigerian National Curriculum" },
  { code: "NO", name: "Norway", nativeCurriculum: "Norway National Curriculum" },
  { code: "PK", name: "Pakistan", nativeCurriculum: "Pakistan National Curriculum" },
  { code: "PH", name: "Philippines", nativeCurriculum: "Philippines National Curriculum" },
  { code: "PL", name: "Poland", nativeCurriculum: "Poland National Curriculum" },
  { code: "PT", name: "Portugal", nativeCurriculum: "Portugal National Curriculum" },
  { code: "QA", name: "Qatar", nativeCurriculum: "Qatar National Curriculum" },
  { code: "RO", name: "Romania", nativeCurriculum: "Romania National Curriculum" },
  { code: "RW", name: "Rwanda", nativeCurriculum: "Rwanda Competence Based Curriculum" },
  { code: "SA", name: "Saudi Arabia", nativeCurriculum: "Saudi National Curriculum" },
  { code: "SN", name: "Senegal", nativeCurriculum: "Senegal National Curriculum" },
  { code: "SL", name: "Sierra Leone", nativeCurriculum: "Sierra Leone National Curriculum" },
  { code: "SG", name: "Singapore", nativeCurriculum: "Singapore National Curriculum" },
  { code: "SO", name: "Somalia", nativeCurriculum: "Somalia National Curriculum" },
  { code: "ZA", name: "South Africa", nativeCurriculum: "CAPS" },
  { code: "ES", name: "Spain", nativeCurriculum: "Spain National Curriculum" },
  { code: "LK", name: "Sri Lanka", nativeCurriculum: "Sri Lanka National Curriculum" },
  { code: "SD", name: "Sudan", nativeCurriculum: "Sudan National Curriculum" },
  { code: "SE", name: "Sweden", nativeCurriculum: "Sweden National Curriculum" },
  { code: "CH", name: "Switzerland", nativeCurriculum: "Switzerland National Curriculum" },
  { code: "TZ", name: "Tanzania", nativeCurriculum: "Tanzania National Curriculum" },
  { code: "TH", name: "Thailand", nativeCurriculum: "Thailand National Curriculum" },
  { code: "UG", name: "Uganda", nativeCurriculum: "Uganda National Curriculum" },
  { code: "UA", name: "Ukraine", nativeCurriculum: "Ukraine National Curriculum" },
  { code: "AE", name: "United Arab Emirates", nativeCurriculum: "UAE National Curriculum" },
  { code: "GB", name: "United Kingdom", nativeCurriculum: "British Curriculum" },
  { code: "US", name: "United States", nativeCurriculum: "American Curriculum" },
  { code: "VN", name: "Vietnam", nativeCurriculum: "Vietnam National Curriculum" },
  { code: "ZM", name: "Zambia", nativeCurriculum: "Zambia National Curriculum" },
  { code: "ZW", name: "Zimbabwe", nativeCurriculum: "Zimbabwe National Curriculum" },
];