export type GeoCity = {
  name: string;
};

export type GeoRegion = {
  code?: string;
  name: string;
  cities?: GeoCity[];
};

export type CountryOption = {
  code: string;
  name: string;
  dialCode: string;
  nativeCurriculum?: string | null;
  regions?: GeoRegion[];
};

export const COUNTRIES: CountryOption[] = [
  { code: "AF", name: "Afghanistan", dialCode: "+93", nativeCurriculum: "Afghanistan National Curriculum", regions: [] },
  { code: "AX", name: "Åland Islands", dialCode: "+358", nativeCurriculum: null, regions: [] },
  { code: "AL", name: "Albania", dialCode: "+355", nativeCurriculum: "Albania National Curriculum", regions: [] },
  { code: "DZ", name: "Algeria", dialCode: "+213", nativeCurriculum: "Algeria National Curriculum", regions: [] },
  { code: "AS", name: "American Samoa", dialCode: "+1", nativeCurriculum: null, regions: [] },
  { code: "AD", name: "Andorra", dialCode: "+376", nativeCurriculum: "Andorra National Curriculum", regions: [] },
  { code: "AO", name: "Angola", dialCode: "+244", nativeCurriculum: "Angola National Curriculum", regions: [] },
  { code: "AI", name: "Anguilla", dialCode: "+1", nativeCurriculum: null, regions: [] },
  { code: "AQ", name: "Antarctica", dialCode: "+672", nativeCurriculum: null, regions: [] },
  { code: "AG", name: "Antigua and Barbuda", dialCode: "+1", nativeCurriculum: "Antigua and Barbuda National Curriculum", regions: [] },
  { code: "AR", name: "Argentina", dialCode: "+54", nativeCurriculum: "Argentina National Curriculum", regions: [] },
  { code: "AM", name: "Armenia", dialCode: "+374", nativeCurriculum: "Armenia National Curriculum", regions: [] },
  { code: "AW", name: "Aruba", dialCode: "+297", nativeCurriculum: null, regions: [] },
  { code: "AU", name: "Australia", dialCode: "+61", nativeCurriculum: "Australian Curriculum", regions: [] },
  { code: "AT", name: "Austria", dialCode: "+43", nativeCurriculum: "Austria National Curriculum", regions: [] },
  { code: "AZ", name: "Azerbaijan", dialCode: "+994", nativeCurriculum: "Azerbaijan National Curriculum", regions: [] },
  { code: "BS", name: "Bahamas", dialCode: "+1", nativeCurriculum: "Bahamas National Curriculum", regions: [] },
  { code: "BH", name: "Bahrain", dialCode: "+973", nativeCurriculum: "Bahrain National Curriculum", regions: [] },
  { code: "BD", name: "Bangladesh", dialCode: "+880", nativeCurriculum: "Bangladesh National Curriculum", regions: [] },
  { code: "BB", name: "Barbados", dialCode: "+1", nativeCurriculum: "Barbados National Curriculum", regions: [] },
  { code: "BY", name: "Belarus", dialCode: "+375", nativeCurriculum: "Belarus National Curriculum", regions: [] },
  { code: "BE", name: "Belgium", dialCode: "+32", nativeCurriculum: "Belgium National Curriculum", regions: [] },
  { code: "BZ", name: "Belize", dialCode: "+501", nativeCurriculum: "Belize National Curriculum", regions: [] },
  { code: "BJ", name: "Benin", dialCode: "+229", nativeCurriculum: "Benin National Curriculum", regions: [] },
  { code: "BM", name: "Bermuda", dialCode: "+1", nativeCurriculum: null, regions: [] },
  { code: "BT", name: "Bhutan", dialCode: "+975", nativeCurriculum: "Bhutan National Curriculum", regions: [] },
  { code: "BO", name: "Bolivia", dialCode: "+591", nativeCurriculum: "Bolivia National Curriculum", regions: [] },
  { code: "BQ", name: "Bonaire, Sint Eustatius and Saba", dialCode: "+599", nativeCurriculum: null, regions: [] },
  { code: "BA", name: "Bosnia and Herzegovina", dialCode: "+387", nativeCurriculum: "Bosnia and Herzegovina National Curriculum", regions: [] },
  { code: "BW", name: "Botswana", dialCode: "+267", nativeCurriculum: "Botswana National Curriculum", regions: [] },
  { code: "BV", name: "Bouvet Island", dialCode: "+47", nativeCurriculum: null, regions: [] },
  { code: "BR", name: "Brazil", dialCode: "+55", nativeCurriculum: "Brazilian National Curriculum", regions: [] },
  { code: "IO", name: "British Indian Ocean Territory", dialCode: "+246", nativeCurriculum: null, regions: [] },
  { code: "BN", name: "Brunei", dialCode: "+673", nativeCurriculum: "Brunei National Curriculum", regions: [] },
  { code: "BG", name: "Bulgaria", dialCode: "+359", nativeCurriculum: "Bulgaria National Curriculum", regions: [] },
  { code: "BF", name: "Burkina Faso", dialCode: "+226", nativeCurriculum: "Burkina Faso National Curriculum", regions: [] },
  { code: "BI", name: "Burundi", dialCode: "+257", nativeCurriculum: "Burundi National Curriculum", regions: [] },
  { code: "CV", name: "Cabo Verde", dialCode: "+238", nativeCurriculum: "Cabo Verde National Curriculum", regions: [] },
  { code: "KH", name: "Cambodia", dialCode: "+855", nativeCurriculum: "Cambodia National Curriculum", regions: [] },
  { code: "CM", name: "Cameroon", dialCode: "+237", nativeCurriculum: "Cameroon National Curriculum", regions: [] },
  { code: "CA", name: "Canada", dialCode: "+1", nativeCurriculum: "Canada Provincial Curricula", regions: [] },
  { code: "KY", name: "Cayman Islands", dialCode: "+1", nativeCurriculum: null, regions: [] },
  { code: "CF", name: "Central African Republic", dialCode: "+236", nativeCurriculum: "Central African Republic National Curriculum", regions: [] },
  { code: "TD", name: "Chad", dialCode: "+235", nativeCurriculum: "Chad National Curriculum", regions: [] },
  { code: "CL", name: "Chile", dialCode: "+56", nativeCurriculum: "Chile National Curriculum", regions: [] },
  { code: "CN", name: "China", dialCode: "+86", nativeCurriculum: "China National Curriculum", regions: [] },
  { code: "CX", name: "Christmas Island", dialCode: "+61", nativeCurriculum: null, regions: [] },
  { code: "CC", name: "Cocos (Keeling) Islands", dialCode: "+61", nativeCurriculum: null, regions: [] },
  { code: "CO", name: "Colombia", dialCode: "+57", nativeCurriculum: "Colombia National Curriculum", regions: [] },
  { code: "KM", name: "Comoros", dialCode: "+269", nativeCurriculum: "Comoros National Curriculum", regions: [] },
  { code: "CG", name: "Congo", dialCode: "+242", nativeCurriculum: "Congo National Curriculum", regions: [] },
  { code: "CD", name: "Congo, The Democratic Republic of the", dialCode: "+243", nativeCurriculum: "DRC National Curriculum", regions: [] },
  { code: "CK", name: "Cook Islands", dialCode: "+682", nativeCurriculum: null, regions: [] },
  { code: "CR", name: "Costa Rica", dialCode: "+506", nativeCurriculum: "Costa Rica National Curriculum", regions: [] },
  { code: "CI", name: "Côte d’Ivoire", dialCode: "+225", nativeCurriculum: "Côte d’Ivoire National Curriculum", regions: [] },
  { code: "HR", name: "Croatia", dialCode: "+385", nativeCurriculum: "Croatia National Curriculum", regions: [] },
  { code: "CU", name: "Cuba", dialCode: "+53", nativeCurriculum: "Cuba National Curriculum", regions: [] },
  { code: "CW", name: "Curaçao", dialCode: "+599", nativeCurriculum: null, regions: [] },
  { code: "CY", name: "Cyprus", dialCode: "+357", nativeCurriculum: "Cyprus National Curriculum", regions: [] },
  { code: "CZ", name: "Czechia", dialCode: "+420", nativeCurriculum: "Czech National Curriculum", regions: [] },
  { code: "DK", name: "Denmark", dialCode: "+45", nativeCurriculum: "Denmark National Curriculum", regions: [] },
  { code: "DJ", name: "Djibouti", dialCode: "+253", nativeCurriculum: "Djibouti National Curriculum", regions: [] },
  { code: "DM", name: "Dominica", dialCode: "+1", nativeCurriculum: "Dominica National Curriculum", regions: [] },
  { code: "DO", name: "Dominican Republic", dialCode: "+1", nativeCurriculum: "Dominican Republic National Curriculum", regions: [] },
  { code: "EC", name: "Ecuador", dialCode: "+593", nativeCurriculum: "Ecuador National Curriculum", regions: [] },
  { code: "EG", name: "Egypt", dialCode: "+20", nativeCurriculum: "Egyptian National Curriculum", regions: [] },
  { code: "SV", name: "El Salvador", dialCode: "+503", nativeCurriculum: "El Salvador National Curriculum", regions: [] },
  { code: "GQ", name: "Equatorial Guinea", dialCode: "+240", nativeCurriculum: "Equatorial Guinea National Curriculum", regions: [] },
  { code: "ER", name: "Eritrea", dialCode: "+291", nativeCurriculum: "Eritrea National Curriculum", regions: [] },
  { code: "EE", name: "Estonia", dialCode: "+372", nativeCurriculum: "Estonia National Curriculum", regions: [] },
  { code: "SZ", name: "Eswatini", dialCode: "+268", nativeCurriculum: "Eswatini National Curriculum", regions: [] },
  { code: "ET", name: "Ethiopia", dialCode: "+251", nativeCurriculum: "Ethiopian National Curriculum", regions: [] },
  { code: "FK", name: "Falkland Islands", dialCode: "+500", nativeCurriculum: null, regions: [] },
  { code: "FO", name: "Faroe Islands", dialCode: "+298", nativeCurriculum: null, regions: [] },
  { code: "FJ", name: "Fiji", dialCode: "+679", nativeCurriculum: "Fiji National Curriculum", regions: [] },
  { code: "FI", name: "Finland", dialCode: "+358", nativeCurriculum: "Finnish National Curriculum", regions: [] },
  { code: "FR", name: "France", dialCode: "+33", nativeCurriculum: "French National Curriculum", regions: [] },
  { code: "GF", name: "French Guiana", dialCode: "+594", nativeCurriculum: null, regions: [] },
  { code: "PF", name: "French Polynesia", dialCode: "+689", nativeCurriculum: null, regions: [] },
  { code: "TF", name: "French Southern Territories", dialCode: "+262", nativeCurriculum: null, regions: [] },
  { code: "GA", name: "Gabon", dialCode: "+241", nativeCurriculum: "Gabon National Curriculum", regions: [] },
  { code: "GM", name: "Gambia", dialCode: "+220", nativeCurriculum: "Gambia National Curriculum", regions: [] },
  { code: "GE", name: "Georgia", dialCode: "+995", nativeCurriculum: "Georgia National Curriculum", regions: [] },
  { code: "DE", name: "Germany", dialCode: "+49", nativeCurriculum: "Germany National Curriculum", regions: [] },
  { code: "GH", name: "Ghana", dialCode: "+233", nativeCurriculum: "Ghana Standards-Based Curriculum", regions: [] },
  { code: "GI", name: "Gibraltar", dialCode: "+350", nativeCurriculum: null, regions: [] },
  { code: "GR", name: "Greece", dialCode: "+30", nativeCurriculum: "Greece National Curriculum", regions: [] },
  { code: "GL", name: "Greenland", dialCode: "+299", nativeCurriculum: null, regions: [] },
  { code: "GD", name: "Grenada", dialCode: "+1", nativeCurriculum: "Grenada National Curriculum", regions: [] },
  { code: "GP", name: "Guadeloupe", dialCode: "+590", nativeCurriculum: null, regions: [] },
  { code: "GU", name: "Guam", dialCode: "+1", nativeCurriculum: null, regions: [] },
  { code: "GT", name: "Guatemala", dialCode: "+502", nativeCurriculum: "Guatemala National Curriculum", regions: [] },
  { code: "GG", name: "Guernsey", dialCode: "+44", nativeCurriculum: null, regions: [] },
  { code: "GN", name: "Guinea", dialCode: "+224", nativeCurriculum: "Guinea National Curriculum", regions: [] },
  { code: "GW", name: "Guinea-Bissau", dialCode: "+245", nativeCurriculum: "Guinea-Bissau National Curriculum", regions: [] },
  { code: "GY", name: "Guyana", dialCode: "+592", nativeCurriculum: "Guyana National Curriculum", regions: [] },
  { code: "HT", name: "Haiti", dialCode: "+509", nativeCurriculum: "Haiti National Curriculum", regions: [] },
  { code: "HM", name: "Heard Island and McDonald Islands", dialCode: "+672", nativeCurriculum: null, regions: [] },
  { code: "VA", name: "Holy See", dialCode: "+379", nativeCurriculum: null, regions: [] },
  { code: "HN", name: "Honduras", dialCode: "+504", nativeCurriculum: "Honduras National Curriculum", regions: [] },
  { code: "HK", name: "Hong Kong", dialCode: "+852", nativeCurriculum: "Hong Kong Curriculum", regions: [] },
  { code: "HU", name: "Hungary", dialCode: "+36", nativeCurriculum: "Hungary National Curriculum", regions: [] },
  { code: "IS", name: "Iceland", dialCode: "+354", nativeCurriculum: "Iceland National Curriculum", regions: [] },
  { code: "IN", name: "India", dialCode: "+91", nativeCurriculum: "CBSE", regions: [] },
  { code: "ID", name: "Indonesia", dialCode: "+62", nativeCurriculum: "Indonesia National Curriculum", regions: [] },
  { code: "IR", name: "Iran", dialCode: "+98", nativeCurriculum: "Iran National Curriculum", regions: [] },
  { code: "IQ", name: "Iraq", dialCode: "+964", nativeCurriculum: "Iraq National Curriculum", regions: [] },
  { code: "IE", name: "Ireland", dialCode: "+353", nativeCurriculum: "Ireland National Curriculum", regions: [] },
  { code: "IM", name: "Isle of Man", dialCode: "+44", nativeCurriculum: null, regions: [] },
  { code: "IL", name: "Israel", dialCode: "+972", nativeCurriculum: "Israel National Curriculum", regions: [] },
  { code: "IT", name: "Italy", dialCode: "+39", nativeCurriculum: "Italy National Curriculum", regions: [] },
  { code: "JM", name: "Jamaica", dialCode: "+1", nativeCurriculum: "Jamaica National Curriculum", regions: [] },
  { code: "JP", name: "Japan", dialCode: "+81", nativeCurriculum: "Japan National Curriculum", regions: [] },
  { code: "JE", name: "Jersey", dialCode: "+44", nativeCurriculum: null, regions: [] },
  { code: "JO", name: "Jordan", dialCode: "+962", nativeCurriculum: "Jordan National Curriculum", regions: [] },
  { code: "KZ", name: "Kazakhstan", dialCode: "+7", nativeCurriculum: "Kazakhstan National Curriculum", regions: [] },
  { code: "KE", name: "Kenya", dialCode: "+254", nativeCurriculum: "CBC", regions: [] },
  { code: "KI", name: "Kiribati", dialCode: "+686", nativeCurriculum: "Kiribati National Curriculum", regions: [] },
  { code: "KP", name: "Korea, Democratic People's Republic of", dialCode: "+850", nativeCurriculum: "North Korea National Curriculum", regions: [] },
  { code: "KR", name: "Korea, Republic of", dialCode: "+82", nativeCurriculum: "South Korea National Curriculum", regions: [] },
  { code: "KW", name: "Kuwait", dialCode: "+965", nativeCurriculum: "Kuwait National Curriculum", regions: [] },
  { code: "KG", name: "Kyrgyzstan", dialCode: "+996", nativeCurriculum: "Kyrgyzstan National Curriculum", regions: [] },
  { code: "LA", name: "Laos", dialCode: "+856", nativeCurriculum: "Laos National Curriculum", regions: [] },
  { code: "LV", name: "Latvia", dialCode: "+371", nativeCurriculum: "Latvia National Curriculum", regions: [] },
  { code: "LB", name: "Lebanon", dialCode: "+961", nativeCurriculum: "Lebanon National Curriculum", regions: [] },
  { code: "LS", name: "Lesotho", dialCode: "+266", nativeCurriculum: "Lesotho National Curriculum", regions: [] },
  { code: "LR", name: "Liberia", dialCode: "+231", nativeCurriculum: "Liberia National Curriculum", regions: [] },
  { code: "LY", name: "Libya", dialCode: "+218", nativeCurriculum: "Libya National Curriculum", regions: [] },
  { code: "LI", name: "Liechtenstein", dialCode: "+423", nativeCurriculum: "Liechtenstein National Curriculum", regions: [] },
  { code: "LT", name: "Lithuania", dialCode: "+370", nativeCurriculum: "Lithuania National Curriculum", regions: [] },
  { code: "LU", name: "Luxembourg", dialCode: "+352", nativeCurriculum: "Luxembourg National Curriculum", regions: [] },
  { code: "MO", name: "Macao", dialCode: "+853", nativeCurriculum: "Macao Curriculum", regions: [] },
  { code: "MG", name: "Madagascar", dialCode: "+261", nativeCurriculum: "Madagascar National Curriculum", regions: [] },
  { code: "MW", name: "Malawi", dialCode: "+265", nativeCurriculum: "Malawi National Curriculum", regions: [] },
  { code: "MY", name: "Malaysia", dialCode: "+60", nativeCurriculum: "Malaysia National Curriculum", regions: [] },
  { code: "MV", name: "Maldives", dialCode: "+960", nativeCurriculum: "Maldives National Curriculum", regions: [] },
  { code: "ML", name: "Mali", dialCode: "+223", nativeCurriculum: "Mali National Curriculum", regions: [] },
  { code: "MT", name: "Malta", dialCode: "+356", nativeCurriculum: "Malta National Curriculum", regions: [] },
  { code: "MH", name: "Marshall Islands", dialCode: "+692", nativeCurriculum: "Marshall Islands National Curriculum", regions: [] },
  { code: "MQ", name: "Martinique", dialCode: "+596", nativeCurriculum: null, regions: [] },
  { code: "MR", name: "Mauritania", dialCode: "+222", nativeCurriculum: "Mauritania National Curriculum", regions: [] },
  { code: "MU", name: "Mauritius", dialCode: "+230", nativeCurriculum: "Mauritius National Curriculum", regions: [] },
  { code: "YT", name: "Mayotte", dialCode: "+262", nativeCurriculum: null, regions: [] },
  { code: "MX", name: "Mexico", dialCode: "+52", nativeCurriculum: "Mexico National Curriculum", regions: [] },
  { code: "FM", name: "Micronesia", dialCode: "+691", nativeCurriculum: "Micronesia National Curriculum", regions: [] },
  { code: "MD", name: "Moldova", dialCode: "+373", nativeCurriculum: "Moldova National Curriculum", regions: [] },
  { code: "MC", name: "Monaco", dialCode: "+377", nativeCurriculum: "Monaco National Curriculum", regions: [] },
  { code: "MN", name: "Mongolia", dialCode: "+976", nativeCurriculum: "Mongolia National Curriculum", regions: [] },
  { code: "ME", name: "Montenegro", dialCode: "+382", nativeCurriculum: "Montenegro National Curriculum", regions: [] },
  { code: "MS", name: "Montserrat", dialCode: "+1", nativeCurriculum: null, regions: [] },
  { code: "MA", name: "Morocco", dialCode: "+212", nativeCurriculum: "Morocco National Curriculum", regions: [] },
  { code: "MZ", name: "Mozambique", dialCode: "+258", nativeCurriculum: "Mozambique National Curriculum", regions: [] },
  { code: "MM", name: "Myanmar", dialCode: "+95", nativeCurriculum: "Myanmar National Curriculum", regions: [] },
  { code: "NA", name: "Namibia", dialCode: "+264", nativeCurriculum: "Namibia National Curriculum", regions: [] },
  { code: "NR", name: "Nauru", dialCode: "+674", nativeCurriculum: "Nauru National Curriculum", regions: [] },
  { code: "NP", name: "Nepal", dialCode: "+977", nativeCurriculum: "Nepal National Curriculum", regions: [] },
  { code: "NL", name: "Netherlands", dialCode: "+31", nativeCurriculum: "Netherlands National Curriculum", regions: [] },
  { code: "NC", name: "New Caledonia", dialCode: "+687", nativeCurriculum: null, regions: [] },
  { code: "NZ", name: "New Zealand", dialCode: "+64", nativeCurriculum: "New Zealand Curriculum", regions: [] },
  { code: "NI", name: "Nicaragua", dialCode: "+505", nativeCurriculum: "Nicaragua National Curriculum", regions: [] },
  { code: "NE", name: "Niger", dialCode: "+227", nativeCurriculum: "Niger National Curriculum", regions: [] },
  { code: "NG", name: "Nigeria", dialCode: "+234", nativeCurriculum: "Nigerian National Curriculum", regions: [] },
  { code: "NU", name: "Niue", dialCode: "+683", nativeCurriculum: null, regions: [] },
  { code: "NF", name: "Norfolk Island", dialCode: "+672", nativeCurriculum: null, regions: [] },
  { code: "MK", name: "North Macedonia", dialCode: "+389", nativeCurriculum: "North Macedonia National Curriculum", regions: [] },
  { code: "MP", name: "Northern Mariana Islands", dialCode: "+1", nativeCurriculum: null, regions: [] },
  { code: "NO", name: "Norway", dialCode: "+47", nativeCurriculum: "Norway National Curriculum", regions: [] },
  { code: "OM", name: "Oman", dialCode: "+968", nativeCurriculum: "Oman National Curriculum", regions: [] },
  { code: "PK", name: "Pakistan", dialCode: "+92", nativeCurriculum: "Pakistan National Curriculum", regions: [] },
  { code: "PW", name: "Palau", dialCode: "+680", nativeCurriculum: "Palau National Curriculum", regions: [] },
  { code: "PS", name: "Palestine, State of", dialCode: "+970", nativeCurriculum: "Palestine National Curriculum", regions: [] },
  { code: "PA", name: "Panama", dialCode: "+507", nativeCurriculum: "Panama National Curriculum", regions: [] },
  { code: "PG", name: "Papua New Guinea", dialCode: "+675", nativeCurriculum: "Papua New Guinea National Curriculum", regions: [] },
  { code: "PY", name: "Paraguay", dialCode: "+595", nativeCurriculum: "Paraguay National Curriculum", regions: [] },
  { code: "PE", name: "Peru", dialCode: "+51", nativeCurriculum: "Peru National Curriculum", regions: [] },
  { code: "PH", name: "Philippines", dialCode: "+63", nativeCurriculum: "Philippines National Curriculum", regions: [] },
  { code: "PN", name: "Pitcairn", dialCode: "+64", nativeCurriculum: null, regions: [] },
  { code: "PL", name: "Poland", dialCode: "+48", nativeCurriculum: "Poland National Curriculum", regions: [] },
  { code: "PT", name: "Portugal", dialCode: "+351", nativeCurriculum: "Portugal National Curriculum", regions: [] },
  { code: "PR", name: "Puerto Rico", dialCode: "+1", nativeCurriculum: null, regions: [] },
  { code: "QA", name: "Qatar", dialCode: "+974", nativeCurriculum: "Qatar National Curriculum", regions: [] },
  { code: "RE", name: "Réunion", dialCode: "+262", nativeCurriculum: null, regions: [] },
  { code: "RO", name: "Romania", dialCode: "+40", nativeCurriculum: "Romania National Curriculum", regions: [] },
  { code: "RU", name: "Russia", dialCode: "+7", nativeCurriculum: "Russia National Curriculum", regions: [] },
  { code: "RW", name: "Rwanda", dialCode: "+250", nativeCurriculum: "Rwanda Competence Based Curriculum", regions: [] },
  { code: "BL", name: "Saint Barthélemy", dialCode: "+590", nativeCurriculum: null, regions: [] },
  { code: "SH", name: "Saint Helena, Ascension and Tristan da Cunha", dialCode: "+290", nativeCurriculum: null, regions: [] },
  { code: "KN", name: "Saint Kitts and Nevis", dialCode: "+1", nativeCurriculum: "Saint Kitts and Nevis National Curriculum", regions: [] },
  { code: "LC", name: "Saint Lucia", dialCode: "+1", nativeCurriculum: "Saint Lucia National Curriculum", regions: [] },
  { code: "MF", name: "Saint Martin", dialCode: "+590", nativeCurriculum: null, regions: [] },
  { code: "PM", name: "Saint Pierre and Miquelon", dialCode: "+508", nativeCurriculum: null, regions: [] },
  { code: "VC", name: "Saint Vincent and the Grenadines", dialCode: "+1", nativeCurriculum: "Saint Vincent and the Grenadines National Curriculum", regions: [] },
  { code: "WS", name: "Samoa", dialCode: "+685", nativeCurriculum: "Samoa National Curriculum", regions: [] },
  { code: "SM", name: "San Marino", dialCode: "+378", nativeCurriculum: "San Marino National Curriculum", regions: [] },
  { code: "ST", name: "Sao Tome and Principe", dialCode: "+239", nativeCurriculum: "Sao Tome and Principe National Curriculum", regions: [] },
  { code: "SA", name: "Saudi Arabia", dialCode: "+966", nativeCurriculum: "Saudi National Curriculum", regions: [] },
  { code: "SN", name: "Senegal", dialCode: "+221", nativeCurriculum: "Senegal National Curriculum", regions: [] },
  { code: "RS", name: "Serbia", dialCode: "+381", nativeCurriculum: "Serbia National Curriculum", regions: [] },
  { code: "SC", name: "Seychelles", dialCode: "+248", nativeCurriculum: "Seychelles National Curriculum", regions: [] },
  { code: "SL", name: "Sierra Leone", dialCode: "+232", nativeCurriculum: "Sierra Leone National Curriculum", regions: [] },
  { code: "SG", name: "Singapore", dialCode: "+65", nativeCurriculum: "Singapore National Curriculum", regions: [] },
  { code: "SX", name: "Sint Maarten", dialCode: "+1", nativeCurriculum: null, regions: [] },
  { code: "SK", name: "Slovakia", dialCode: "+421", nativeCurriculum: "Slovakia National Curriculum", regions: [] },
  { code: "SI", name: "Slovenia", dialCode: "+386", nativeCurriculum: "Slovenia National Curriculum", regions: [] },
  { code: "SB", name: "Solomon Islands", dialCode: "+677", nativeCurriculum: "Solomon Islands National Curriculum", regions: [] },
  { code: "SO", name: "Somalia", dialCode: "+252", nativeCurriculum: "Somalia National Curriculum", regions: [] },
  { code: "ZA", name: "South Africa", dialCode: "+27", nativeCurriculum: "CAPS", regions: [] },
  { code: "GS", name: "South Georgia and the South Sandwich Islands", dialCode: "+500", nativeCurriculum: null, regions: [] },
  { code: "SS", name: "South Sudan", dialCode: "+211", nativeCurriculum: "South Sudan National Curriculum", regions: [] },
  { code: "ES", name: "Spain", dialCode: "+34", nativeCurriculum: "Spain National Curriculum", regions: [] },
  { code: "LK", name: "Sri Lanka", dialCode: "+94", nativeCurriculum: "Sri Lanka National Curriculum", regions: [] },
  { code: "SD", name: "Sudan", dialCode: "+249", nativeCurriculum: "Sudan National Curriculum", regions: [] },
  { code: "SR", name: "Suriname", dialCode: "+597", nativeCurriculum: "Suriname National Curriculum", regions: [] },
  { code: "SJ", name: "Svalbard and Jan Mayen", dialCode: "+47", nativeCurriculum: null, regions: [] },
  { code: "SE", name: "Sweden", dialCode: "+46", nativeCurriculum: "Sweden National Curriculum", regions: [] },
  { code: "CH", name: "Switzerland", dialCode: "+41", nativeCurriculum: "Switzerland National Curriculum", regions: [] },
  { code: "SY", name: "Syria", dialCode: "+963", nativeCurriculum: "Syria National Curriculum", regions: [] },
  { code: "TW", name: "Taiwan", dialCode: "+886", nativeCurriculum: "Taiwan National Curriculum", regions: [] },
  { code: "TJ", name: "Tajikistan", dialCode: "+992", nativeCurriculum: "Tajikistan National Curriculum", regions: [] },
  { code: "TZ", name: "Tanzania", dialCode: "+255", nativeCurriculum: "Tanzania National Curriculum", regions: [] },
  { code: "TH", name: "Thailand", dialCode: "+66", nativeCurriculum: "Thailand National Curriculum", regions: [] },
  { code: "TL", name: "Timor-Leste", dialCode: "+670", nativeCurriculum: "Timor-Leste National Curriculum", regions: [] },
  { code: "TG", name: "Togo", dialCode: "+228", nativeCurriculum: "Togo National Curriculum", regions: [] },
  { code: "TK", name: "Tokelau", dialCode: "+690", nativeCurriculum: null, regions: [] },
  { code: "TO", name: "Tonga", dialCode: "+676", nativeCurriculum: "Tonga National Curriculum", regions: [] },
  { code: "TT", name: "Trinidad and Tobago", dialCode: "+1", nativeCurriculum: "Trinidad and Tobago National Curriculum", regions: [] },
  { code: "TN", name: "Tunisia", dialCode: "+216", nativeCurriculum: "Tunisia National Curriculum", regions: [] },
  { code: "TR", name: "Türkiye", dialCode: "+90", nativeCurriculum: "Türkiye National Curriculum", regions: [] },
  { code: "TM", name: "Turkmenistan", dialCode: "+993", nativeCurriculum: "Turkmenistan National Curriculum", regions: [] },
  { code: "TC", name: "Turks and Caicos Islands", dialCode: "+1", nativeCurriculum: null, regions: [] },
  { code: "TV", name: "Tuvalu", dialCode: "+688", nativeCurriculum: "Tuvalu National Curriculum", regions: [] },
  { code: "UG", name: "Uganda", dialCode: "+256", nativeCurriculum: "Uganda National Curriculum", regions: [] },
  { code: "UA", name: "Ukraine", dialCode: "+380", nativeCurriculum: "Ukraine National Curriculum", regions: [] },
  { code: "AE", name: "United Arab Emirates", dialCode: "+971", nativeCurriculum: "UAE National Curriculum", regions: [] },
  { code: "GB", name: "United Kingdom", dialCode: "+44", nativeCurriculum: "British Curriculum", regions: [] },
  { code: "US", name: "United States", dialCode: "+1", nativeCurriculum: "American Curriculum", regions: [] },
  { code: "UM", name: "United States Minor Outlying Islands", dialCode: "+1", nativeCurriculum: null, regions: [] },
  { code: "UY", name: "Uruguay", dialCode: "+598", nativeCurriculum: "Uruguay National Curriculum", regions: [] },
  { code: "UZ", name: "Uzbekistan", dialCode: "+998", nativeCurriculum: "Uzbekistan National Curriculum", regions: [] },
  { code: "VU", name: "Vanuatu", dialCode: "+678", nativeCurriculum: "Vanuatu National Curriculum", regions: [] },
  { code: "VE", name: "Venezuela", dialCode: "+58", nativeCurriculum: "Venezuela National Curriculum", regions: [] },
  { code: "VN", name: "Vietnam", dialCode: "+84", nativeCurriculum: "Vietnam National Curriculum", regions: [] },
  { code: "VG", name: "Virgin Islands, British", dialCode: "+1", nativeCurriculum: null, regions: [] },
  { code: "VI", name: "Virgin Islands, U.S.", dialCode: "+1", nativeCurriculum: null, regions: [] },
  { code: "WF", name: "Wallis and Futuna", dialCode: "+681", nativeCurriculum: null, regions: [] },
  { code: "EH", name: "Western Sahara", dialCode: "+212", nativeCurriculum: null, regions: [] },
  { code: "YE", name: "Yemen", dialCode: "+967", nativeCurriculum: "Yemen National Curriculum", regions: [] },
  { code: "ZM", name: "Zambia", dialCode: "+260", nativeCurriculum: "Zambia National Curriculum", regions: [] },
  { code: "ZW", name: "Zimbabwe", dialCode: "+263", nativeCurriculum: "Zimbabwe National Curriculum", regions: [] },
];

export const COUNTRY_BY_CODE = Object.fromEntries(
  COUNTRIES.map((country) => [country.code, country])
) as Record<string, CountryOption>;

export const COUNTRY_OPTIONS = COUNTRIES.map((country) => ({
  code: country.code,
  name: country.name,
  dialCode: country.dialCode,
}));

export function getCountryByCode(code?: string | null) {
  if (!code) return null;
  return COUNTRY_BY_CODE[code.toUpperCase()] ?? null;
}

export function searchCountries(query: string) {
  const normalized = query.trim().toLowerCase();

  if (!normalized) return COUNTRIES;

  return COUNTRIES.filter((country) => {
    const curriculum = country.nativeCurriculum?.toLowerCase() ?? "";
    return (
      country.name.toLowerCase().includes(normalized) ||
      country.code.toLowerCase().includes(normalized) ||
      country.dialCode.toLowerCase().includes(normalized) ||
      curriculum.includes(normalized)
    );
  });
}